# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 06 Sep 2020 21:05:15 +0000
*               @ALL          1
*               @user         8
