# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 25 Nov 2017 17:49:32 +0000
*	@ALL	1
*	@user	8
dokumenty:*	@user	1
dokumenty:*	ksiadz	8
dokumenty:*	amadeusz	8
dokumenty:regulaminy:warsztat	yazjack	2
finanse:*	@user	1
finanse:*	amadeusz	8
finanse:chciejlista	@user	1
finanse:chciejlista	@member	2
ludzie:*	@ALL	0
ludzie:*	@user	4
playground:*	@bot	4
strefa:*	@ALL	0
strefa:*	@user	0
strefa:*	@member	4
dokumenty:*	@manager	16
